version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=hjxenjoy
      - MONGO_PASSWORD=enjoypwd
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hjxenjoy
      - MONGO_INITDB_ROOT_PASSWORD=enjoypwd

